site_name: 键盘开发文档
site_url: https://ljturing.github.io/the-ljturing-studio/

repo_name: 键盘开发文档
repo_url: https://github.com/LJTuring/the-ljturing-studio

edit_uri: edit/master/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    code: Roboto Mono
  language: zh
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide

nav:
  - 主页: index.md
  - AMK配置: amk_config.md
  - KMK配置: kmk_config.md
  - QMK配置: qmk_config.md
  - RMK配置: rmk_config.md
  - ZMK配置: zmk_config.md
  - 其他: other.md

markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - admonition
    - pymdownx.details
    - tables
    - footnotes
    - def_list
    - meta

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LJTuring/the-ljturing-studio
      name: The LJTuring Studio
  generator: false

copyright: 由 LJTuring &boxbox; 创建和维护

