site_name: 键盘开发文档
site_url: https://ljturing.github.io/the_ljturing_studio/
repo_url: https://github.com/LJTuring/the_ljturing_studio

theme:
    name: material
    palette: 
        scheme: slate
        primary: black
        accent: green
    logo: assets/logo.png
    icon:
        repo: fontawesome/brands/github
    favicon: images/favicon.png
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - header.autohide
        - navigation.footer

nav:
    - 主页: index.md
    - AMK配置: amk_config.md
    - KMK配置: kmk_config.md
    - QMK配置: qmk_config.md
    - RMK配置: rmk_config.md
    - ZMK配置: zmk_config.md
    - 其他: other.md

markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - admonition
    - pymdownx.details
    - tables
    - footnotes
    - def_list

extra:
    social:
        - icon: fontawesome/brands/github
            link: https://github.com/LJTuring/the_ljturing_studio

copyright: Created and maintained by LJTuring
